test

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -22,6 +22,9 @@ jobs:
           export-type: "file"
           file-output-path: ".env.infisical"
 
+      - name: Debug check .env.infisical
+        run: ls -l .env.infisical || echo "Missing .env.infisical"
+
       - name: Parse arguments and variables
         id: prep
         run: |
